import { Product, Testimonial } from './types';

export const products: Product[] = [
  {
    id: 'honey-flowers',
    name: 'عسل زهور سوس الفاخر',
    nameAr: 'عسل زهور سوس الفاخر',
    nameFr: "Miel de Fleurs de Souss Premium",
    nameEn: 'Premium Souss Flower Honey',
    category: 'honey',
    categoryAr: 'العسل',
    price: 150,
    description: 'مزيج عطري نقي مستخلص من أزهار البراري الطبيعية في ربوع سوس المعطاء.',
    descriptionAr: 'مزيج عطري نقي مستخلص من أزهار البراري الطبيعية في ربوع سوس المعطاء.',
    descriptionFr: 'Un mélange aromatique pur extrait des fleurs sauvages de la région de Souss.',
    descriptionEn: 'A pure aromatic blend extracted from wild mountain flowers in the Souss region.',
    longDescription: 'عسل طبيعي ممتاز يتميز بلونه الذهبي الفاتح ونكهته العطرية الخفيفة المحببة للأطفال والكبار. يجنيه النحل من زهور مزارع وبراري سوس المعطاء المتنوعة مثل الزعتر والدردار والخزامى في بيئة نقية تماماً بعيدة عن التلوث.',
    longDescriptionAr: 'عسل طبيعي ممتاز يتميز بلونه الذهبي الفاتح ونكهته العطرية الخفيفة المحببة للأطفال والكبار. يجنيه النحل من زهور مزارع وبراري سوس المعطاء المتنوعة مثل الزعتر والدردار والخزامى في بيئة نقية تماماً بعيدة عن التلوث.',
    longDescriptionFr: 'Miel de qualité supérieure, caractérisé par sa couleur dorée claire et sa saveur aromatique douce appréciée de tous. Récolté dans un environnement vierge et préservé de la région de Souss.',
    longDescriptionEn: 'Premium natural honey featuring a light golden color and mild aromatic flavor. Harvested by bees from diverse wild flowers in a pristine, pollution-free Souss environment.',
    benefits: ['منشط طبيعي للمناعة والجسد', 'بديل ممتاز وصحي للسكر المكرر', 'مهدئ للسعال ومحسن لعملية الهضم'],
    benefitsAr: ['منشط طبيعي للمناعة والجسد', 'بديل ممتاز وصحي للسكر المكرر', 'مهدئ للسعال ومحسن لعملية الهضم'],
    benefitsFr: ['Stimulant naturel de l’immunité et du corps', 'Alternative saine au sucre raffiné', 'Calme la toux et améliore la digestion'],
    benefitsEn: ['Natural booster for immunity and body', 'Healthy alternative to refined sugar', 'Soothes cough and improves digestive health'],
    weight: '500 غرام',
    weightAr: '500 غرام',
    weightFr: '500g',
    weightEn: '500g',
    image: '/images/premium_honey_jar.webp',
    isBestSeller: true
  },
  {
    id: 'honey-sidr',
    name: 'عسل السدر السوسي الحر',
    nameAr: 'عسل السدر السوسي الحر',
    nameFr: "Miel de Sidr de Souss Pur",
    nameEn: 'Pure Souss Sidr Honey',
    category: 'honey',
    categoryAr: 'العسل',
    price: 360,
    description: 'عسل ملكي فاخر، مستخلص من شجر النبق (السدر) البري في الأودية الدافئة بمنطقة سوس.',
    descriptionAr: 'عسل ملكي فاخر، مستخلص من شجر النبق (السدر) البري في الأودية الدافئة بمنطقة سوس.',
    descriptionFr: 'Miel royal de luxe, récolté sur les jujubiers sauvages des vallées de Souss.',
    descriptionEn: 'Luxury royal honey, harvested from wild Sidr (Lote) trees in warm Souss valleys.',
    longDescription: 'أحد أندر وأنقى أنواع العسل في المغرب. يجمع النحل هذا العسل من زهور شجر السدر البري في أودية سوس الدافئة. يمتاز بلونه الكهرماني الداكن وقوامه اللزج الكثيف ونكهته العميقة التي تدوم طويلاً، ويعتبر صيدلية طبيعية متكاملة.',
    longDescriptionAr: 'أحد أندر وأنقى أنواع العسل في المغرب. يجمع النحل هذا العسل من زهور شجر السدر البري في أودية سوس الدافئة. يمتاز بلونه الكهرماني الداكن وقوامه اللزج الكثيف ونكهته العميقة التي تدوم طويلاً، ويعتبر صيدلية طبيعية متكاملة.',
    longDescriptionFr: 'L’un des miels les plus rares et les plus purs du Maroc. Caractérisé par sa couleur ambrée foncée, sa texture dense et son goût profond et persistant. Une véritable pharmacie naturelle.',
    longDescriptionEn: 'One of the rarest and purest honeys in Morocco. Harvested from wild Sidr tree blossoms in warm Souss valleys, it features a dark amber color, thick density, and a deep lingering taste.',
    benefits: ['مضاد طبيعي قوي للالتهابات والميكروبات', 'يساعد في التئام الجروح وتجديد خلايا البشرة', 'منشط عام ومفيد جداً للجهاز الهضمي'],
    benefitsAr: ['مضاد طبيعي قوي للالتهابات والميكروبات', 'يساعد في التئام الجروح وتجديد خلايا البشرة', 'منشط عام ومفيد جداً للجهاز الهضمي'],
    benefitsFr: ['Puissant anti-inflammatoire et antimicrobien naturel', 'Aide à la cicatrisation et régénération de la peau', 'Tonique général bénéfique pour le système digestif'],
    benefitsEn: ['Powerful natural anti-inflammatory and antimicrobial agent', 'Helps in wound healing and skin cell renewal', 'General tonic and highly beneficial for digestion'],
    weight: '500 غرام',
    weightAr: '500 غرام',
    weightFr: '500g',
    weightEn: '500g',
    image: '/images/premium_honey_jar.webp'
  },
  {
    id: 'honey-harsha',
    name: 'عسل الحرشة الجبلي (زعتر بري سوسي)',
    nameAr: 'عسل الحرشة الجبلي (زعتر بري سوسي)',
    nameFr: 'Miel de Thym Sauvage de Souss (Harsha)',
    nameEn: 'Souss Thyme Honey (Harsha)',
    category: 'honey',
    categoryAr: 'العسل',
    price: 190,
    description: 'عسل نحل يتغذى على نبات الزعتر الجبلي، قوي الطعم وعالي الفوائد التنفسية.',
    descriptionAr: 'عسل نحل يتغذى على نبات الزعتر الجبلي، قوي الطعم وعالي الفوائد التنفسية.',
    descriptionFr: 'Issu du thym de montagne sauvage, fort en goût avec d’excellentes vertus respiratoires.',
    descriptionEn: 'Honey from mountain thyme nectar, strong taste with incredible respiratory benefits.',
    longDescription: 'عسل أصيل ذو لون ذهبي داكن يميل للاحمرار، يستخلصه النحل من نبات الزعتر الجبلي البري (المعروف محلياً بالحرشة) المنتشر بمرتفعات سوس العريقة. يمتاز بلسعة قوية فريدة وفوائد مطهرة ممتازة.',
    longDescriptionAr: 'عسل أصيل ذو لون ذهبي داكن يميل للاحمرار، يستخلصه النحل من نبات الزعتر الجبلي البري (المعروف محلياً بالحرشة) المنتشر بمرتفعات سوس العريقة. يمتاز بلسعة قوية فريدة وفوائد مطهرة ممتازة.',
    longDescriptionFr: 'Miel authentique de couleur dorée foncée aux reflets rougeâtres, produit à partir du thym sauvage des hauteurs de Souss. Réputé pour ses vertus antiseptiques exceptionnelles.',
    longDescriptionEn: 'Authentic dark golden honey with reddish hues, extracted by bees from Souss wild thyme. Famous for its unique pungent note and excellent natural antiseptic benefits.',
    benefits: ['مهدئ ممتاز لنزلات البرد والجهاز التنفسي', 'غني جداً بمضادات الأكسدة والمعادن الأساسية', 'مطهر معوي طبيعي ومنشط للدورة الدموية'],
    benefitsAr: ['مهدئ ممتاز لنزلات البرد والجهاز التنفسي', 'غني جداً بمضادات الأكسدة والمعادن الأساسية', 'مطهر معوي طبيعي ومنشط للدورة الدموية'],
    benefitsFr: ['Soulagement des rhumes et voies respiratoires', 'Très riche en antioxydants et minéraux essentiels', 'Antiseptique intestinal naturel et stimulant'],
    benefitsEn: ['Excellent soothing agent for colds and respiratory system', 'Rich in antioxidants and vital minerals', 'Natural intestinal antiseptic and circulatory stimulant'],
    weight: '500 غرام',
    weightAr: '500 غرام',
    weightFr: '500g',
    weightEn: '500g',
    image: '/images/premium_honey_jar.webp',
    isBestSeller: true
  },
  {
    id: 'amlou-almond',
    name: 'أملو اللوز البلدي وزيت الأركان الفاخر',
    nameAr: 'أملو اللوز البلدي وزيت الأركان الفاخر',
    nameFr: "Amlou aux Amandes et Huile d'Argan",
    nameEn: 'Authentic Almond and Argan Oil Amlou',
    category: 'amlou',
    categoryAr: 'أملو',
    price: 130,
    description: 'الوصفة الأمازيغية التقليدية: لوز بلدي محمص، زيت أركان معصور على البارد، وعسل نحل طبيعي.',
    descriptionAr: 'الوصفة الأمازيغية التقليدية: لوز بلدي محمص، زيت أركان معصور على البارد، وعسل نحل طبيعي.',
    descriptionFr: 'Recette berbère traditionnelle : amandes grillées, huile d’argan extraite à froid et miel pur.',
    descriptionEn: 'Traditional Berber recipe: roasted local almonds, cold-pressed culinary argan oil, and pure honey.',
    longDescription: 'أملو أمازيغي أصيل ١٠٠٪ محضر يدوياً من أجود حبات اللوز البلدي المحمص في أفران طينية تقليدية، مطحون بلطف بحجر الرحى التقليدي وممزوج بزيت الأركان الصافي وعسل النحل الطبيعي لتقديم تجربة تذوق غنية ومغذية بالكامل.',
    longDescriptionAr: 'أملو أمازيغي أصيل ١٠٠٪ محضر يدوياً من أجود حبات اللوز البلدي المحمص في أفران طينية تقليدية، مطحون بلطف بحجر الرحى التقليدي وممزوج بزيت الأركان الصافي وعسل النحل الطبيعي لتقديم تجربة تذوق غنية ومغذية بالكامل.',
    longDescriptionFr: 'Amlou berbère 100% authentique préparé à la main à partir d’amandes locales grillées dans des fours d’argile traditionnels, moulu à la meule de pierre et mélangé à de l’huile d’argan pure et du miel brut.',
    longDescriptionEn: '100% authentic Berber Amlou handmade from the finest local almonds roasted in traditional clay ovens, stone-ground and blended with pure culinary argan oil and raw honey.',
    benefits: ['مصدر هائل للطاقة والدهون الصحية غير المشبعة', 'غني بفيتامين E ومضادات الأكسدة المغذية للبشرة والشعر', 'خالٍ تماماً من الزيوت المهدرجة أو السكريات المضافة'],
    benefitsAr: ['مصدر هائل للطاقة والدهون الصحية غير المشبعة', 'غني بفيتامين E ومضادات الأكسدة المغذية للبشرة والشعر', 'خالٍ تماماً من الزيوت المهدرجة أو السكريات المضافة'],
    benefitsFr: ['Excellente source d’énergie et de graisses saines', 'Riche en vitamine E et antioxydants pour le corps', 'Sans huiles hydrogénées ni sucres raffinés ajoutés'],
    benefitsEn: ['Terrific source of energy and unsaturated healthy fats', 'Rich in Vitamin E and antioxidants nourishing skin and hair', '100% free of hydrogenated oils or added sugars'],
    weight: '500 غرام',
    weightAr: '500 غرام',
    weightFr: '500g',
    weightEn: '500g',
    image: '/images/traditional_amlou_jar.webp',
    isBestSeller: true
  },
  {
    id: 'amlou-walnut',
    name: 'أملو الجوز (الكركاع) الملكي بعسل السدر',
    nameAr: 'أملو الجوز (الكركاع) الملكي بعسل السدر',
    nameFr: 'Amlou Royal aux Noix et Miel de Sidr',
    nameEn: 'Royal Walnut Amlou with Sidr Honey',
    category: 'amlou',
    categoryAr: 'أملو',
    price: 195,
    description: 'خلطة النخبة: يجمع بين الجوز البلدي المحمص، اللوز، زيت الأركان الصافي وعسل السدر الفاخر.',
    descriptionAr: 'خلطة النخبة: يجمع بين الجوز البلدي المحمص، اللوز، زيت الأركان الصافي وعسل السدر الفاخر.',
    descriptionFr: 'Mélange d’élite : allie noix locales, amandes, huile d’argan pure et miel de Sidr précieux.',
    descriptionEn: 'Elite blend: combining roasted walnuts, almonds, pure argan oil, and luxurious Sidr honey.',
    longDescription: 'ابتكار فاخر وخاص بتعاونيتنا لتقديم تجربة تذوق استثنائية. نمزج جوز مزارع سوس (الكركاع) الغني باللوز المحمص، ونعجنه بزيت الأركان الصافي، ثم نضفي عليه حلاوة دافئة وعلاجية باستخدام عسل السدر الطبيعي.',
    longDescriptionAr: 'ابتكار فاخر وخاص بتعاونيتنا لتقديم تجربة تذوق استثنائية. نمزج جوز مزارع سوس (الكركاع) الغني باللوز المحمص، ونعجنه بزيت الأركان الصافي، ثم نضفي عليه حلاوة دافئة وعلاجية باستخدام عسل السدر الطبيعي.',
    longDescriptionFr: 'Une création unique de notre coopérative : mélange de noix de Souss et d’amandes, liées à l’huile d’argan pure et adoucies au miel thérapeutique de Sidr.',
    longDescriptionEn: 'A luxury innovation exclusive to our cooperative. We blend rich Souss walnuts and almonds, knead them with pure argan oil, and finish with the warm healing touch of Sidr honey.',
    benefits: ['غني بأحماض أوميغا ٣ الهامة لصحة الدماغ والتركيز', 'وجبة صباحية مثالية للرياضيين والأطفال للنشاط الذهني', 'قوام كريمي فاخر ومذاق متداخل غاية في التعقيد والمتعة'],
    benefitsAr: ['غني بأحماغ أوميغا ٣ الهامة لصحة الدماغ والتركيز', 'وجبة صباحية مثالية للرياضيين والأطفال للنشاط الذهني', 'قوام كريمي فاخر ومذاق متداخل غاية في التعقيد والمتعة'],
    benefitsFr: ['Riche en oméga-3 essentiels pour le cerveau et la mémoire', 'Petit-déjeuner idéal pour le tonus des sportifs et enfants', 'Texture crémeuse exquise et saveurs complexes'],
    benefitsEn: ['Highly rich in Omega-3 fatty acids for brain health and focus', 'Perfect morning breakfast booster for athletes and kids', 'Luxurious creamy texture and complex deeply satisfying taste'],
    weight: '500 غرام',
    weightAr: '500 غرام',
    weightFr: '500g',
    weightEn: '500g',
    image: '/images/traditional_amlou_jar.webp'
  },
  {
    id: 'rare-wild-souss',
    name: 'عسل جبال سوس الحر النادر',
    nameAr: 'عسل جبال سوس الحر النادر',
    nameFr: 'Miel Sauvage de Souss Rare',
    nameEn: 'Rare Wild Souss Mountain Honey',
    category: 'honey',
    categoryAr: 'العسل',
    price: 290,
    description: 'مستخلص من مناحلنا في ربوع سوس المعطاء، محصود بكميات محدودة جداً في الموسم.',
    descriptionAr: 'مستخلص من مناحلنا في ربوع سوس المعطاء، محصود بكميات محدودة جداً في الموسم.',
    descriptionFr: 'Récolté dans nos ruchers d’altitude dans la région de Souss, quantités très limitées par an.',
    descriptionEn: 'Harvested from our high-altitude apiaries in Souss, extremely limited quantity.',
    longDescription: 'عسل بري عالي الارتفاع يجمع بين الخصائص النادرة لأكثر من ٢٥ زهرة برية وعشب طبيعي ينمو في ربوع سوس الشاهقة. هذا العسل يمثل جوهر الطبيعة العذراء ويمتاز بقوام ثقيل ولون كهرماني عميق جداً.',
    longDescriptionAr: 'عسل بري عالي الارتفاع يجمع بين الخصائص النادرة لأكثر من ٢٥ زهرة برية وعشب طبيعي ينمو في ربوع سوس الشاهقة. هذا العسل يمثل جوهر الطبيعة العذراء ويمتاز بقوام ثقيل ولون كهرماني عميق جداً.',
    longDescriptionFr: 'Miel sauvage d’altitude, qui réunit les propriétés uniques de plus de 25 fleurs de montagne et herbes médicinales de Souss. Texture dense et couleur ambrée très profonde.',
    longDescriptionEn: 'A high-altitude wild honey combining the properties of over 25 wild flowers and herbs that grow in the majestic Souss peaks. Features a heavy texture and very deep amber color.',
    benefits: ['قوة شفائية هائلة موروثة جيلًا بعد جيل', 'يساعد في تجديد النشاط وتوازن الهرمونات طبيعياً', 'نكهة برية معقدة بلمحات الخشب والأعشاب الجافة'],
    benefitsAr: ['قوة شفائية هائلة موروثة جيلًا بعد جيل', 'يساعد في تجديد النشاط وتوازن الهرمونات طبيعياً', 'نكهة برية معقدة بلمحات الخشب والأعشاب الجافة'],
    benefitsFr: ['Puissantes propriétés médicinales ancestrales', 'Aide à renouveler la vitalité et équilibrer l’organisme', 'Goût sauvage et complexe avec des notes boisées'],
    benefitsEn: ['Tremendous healing power passed down through generations', 'Helps restore natural energy levels and hormonal balance', 'Complex woody flavor profile with hints of dried mountain herbs'],
    weight: '500 غرام',
    weightAr: '500 غرام',
    weightFr: '500g',
    weightEn: '500g',
    image: '/images/premium_honey_jar.webp'
  },
  {
    id: 'rare-chendgoura',
    name: 'عسل الجعدة البري (الشندكورة)',
    nameAr: 'عسل الجعدة البري (الشندكورة)',
    nameFr: 'Miel de Germandrée Sauvage (Chendgoura)',
    nameEn: 'Wild Teucrium Mountain Honey (Chendgoura)',
    category: 'honey',
    categoryAr: 'العسل',
    price: 250,
    description: 'عسل طبيعي معزز بفوائد نبتة الشندكورة البرية، يفضله الباحثون عن الاستشفاء الطبيعي.',
    descriptionAr: 'عسل طبيعي معزز بفوائد نبتة الشندكورة البرية، يفضله الباحثون عن الاستشفاء الطبيعي.',
    descriptionFr: 'Miel naturel doté des vertus de la plante sauvage de germandrée, idéal pour l’herboristerie.',
    descriptionEn: 'Pure honey infused with the therapeutic values of wild Teucrium, favored for holistic health.',
    longDescription: 'عسل خالص مأخوذ من رحيق نبات الجعدة البرية (الشندكورة) المشهورة في الطب الشعبي المغربي بجهة سوس المعطاء. طعمه مرارته خفيفة محببة، ويعد من الأعسال الطبية التي يصفها خبراء التغذية البديلة لخصائصها الفريدة ومحدودية إنتاجها السنوي.',
    longDescriptionAr: 'عسل خالص مأخوذ من رحيق نبات الجعدة البرية (الشندكورة) المشهورة في الطب الشعبي المغربي بجهة سوس المعطاء. طعمه مرارته خفيفة محببة، ويعد من الأعسال الطبية التي يصفها خبراء التغذية البديلة لخصائصها الفريدة ومحدودية إنتاجها السنوي.',
    longDescriptionFr: 'Miel de Souss pur issu de la germandrée sauvage (Chendgoura), très prisée en médecine traditionnelle marocaine. Présente une légère amertume agréable et d’excellentes propriétés thérapeutique.',
    longDescriptionEn: 'Pure Souss honey harvested from wild Teucrium (locally Chendgoura) famous in Moroccan folklore. Features a pleasant slight bitterness, highly prized by alternative health experts.',
    benefits: ['داعم ممتاز للجهاز الهضمي وتخفيف آلام المعدة والقولون', 'يساعد في تنظيم مستويات السكر في الدم بالجرعات المناسبة', 'منظف طبيعي للجسم والسموم ومقوي للكبد والبنكرياس'],
    benefitsAr: ['داعم ممتاز للجهاز الهضمي وتخفيف آلام المعدة والقولون', 'يساعد في تنظيم مستويات السكر في الدم بالجرعات المناسبة', 'منظف طبيعي للجسم والسموم ومقوي للكبد والبنكرياس'],
    benefitsFr: ['Soutien digestif et soulagement de l’estomac et colon', 'Aide à réguler la glycémie avec un dosage adapté', 'Détoxifiant corporel naturel fortifiant pour le foie'],
    benefitsEn: ['Superb digestive support, relieving stomach discomfort and colon', 'Aids in blood sugar regulation in appropriate dosages', 'Natural body detoxifier, strengthening liver and pancreas functions'],
    weight: '500 غرام',
    weightAr: '500 غرام',
    weightFr: '500g',
    weightEn: '500g',
    image: '/images/premium_honey_jar.webp'
  }
];

export const testimonials: Testimonial[] = [
  {
    id: 't-1',
    name: 'أمينة بن يوسف',
    role: 'خبيرة تغذية طبيعية',
    location: 'الدار البيضاء',
    content: 'أملو Coopérative Tadmamte هو الأفضل بلا منازع! جودة زيت الأركان واضحة وحلاوته نابعة من عسل حقيقي وليس سكر مستتر كالمتاجر التجارية. أنصح به كل مراجعي وعائلتي.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&h=150&q=80'
  },
  {
    id: 't-2',
    name: 'رشيد أومولود',
    role: 'محب للمنتجات الطبيعية والأصيلة',
    location: 'أكادير',
    content: 'أشتري عسل السدر السوسي والزعتر من Coopérative Tadmamte بانتظام. النقاء والذوق لا تشوبه شائبة، وتغليف المنتجات في قوارير زجاجية أنيقة يشعرك بالفخامة قبل تذوقه. الشحن سريع ومهذب جداً.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&h=150&q=80'
  },
  {
    id: 't-3',
    name: 'فاطمة الزهراء البهجة',
    role: 'مصممة أزياء تراثية المغرب',
    location: 'مراكش',
    content: 'أحببت قصة النساء وراء المشروع وتأثرت كثيراً بالجهد اليدوي والأمانة في الإنتاج. العسل برائحته يذكرني بطفولتي في قرى سوس. تصميم المتجر وتجربة الشراء ممتعة وتليق بالتراث الفاخر.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&h=150&q=80'
  },
  {
    id: 't-4',
    name: 'فاضمة إيت باها',
    role: 'عضوة في Coopérative Tadmamte',
    location: 'تارودانت، سوس',
    content: 'التعاونية وفرت لنا نحن نساء القرية بيئة آمنة للعمل ودخلاً كريماً نصون به كرامة بيوتنا. كل قطرة عسل أو حبة أملو نصنعها بقلوبنا ودعائنا بالبركة لمن يتذوقها.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=150&h=150&q=80'
  }
];

export const shippingBenefits = [
  {
    title: 'توصيل سريع وآمن',
    desc: 'نشحن لجميع مدن المغرب في غضون ٢٤ إلى ٤٨ ساعة في تغليف مخصص لحماية الزجاج.'
  },
  {
    title: 'الدفع عند الاستلام',
    desc: 'لا حاجة لبطاقة ائتمانية. اطلب منتجاتك وافحصها بنفسك، ثم ادفع للموزع عند الاستلام.'
  },
  {
    title: 'دعم استقلالية النساء',
    desc: '١٠٠٪ من أرباح المتجر تذهب لدعم نساء سوس وتطوير مشاريعهن المعيشية.'
  }
];
